config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :programs, only: [:index, :show] do
    resources :reviews, shallow: true
    resources :watchings, only: :create
    resources :favorites, only: [:create, :destroy]
  end

  get "/dashboard", to: "dashboards#show", as: :dashboard

  resources :children, only: [:create, :destroy]

  resources :watchings, except: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :children_watchings, only: [:index, :create]
  end
  resources :children_watchings, only: :destroy
  resources :accounts, only: [:new, :create, :destroy]
end

app/models/children_watching.rb
class ChildrenWatching < ApplicationRecord
  belongs_to :child
  belongs_to :watching
end

app/controllers/children_watchings_controller.rb
class ChildrenWatchingsController < ApplicationController
  def index
    @children_watching = ChildrenWatching.new
    @watching = Watching.find(params[:watching_id])
    @children_watchings = @watching.children_watchings
    @user = current_user
  end

  def create
    @children_watching = ChildrenWatching.new
    @watching = Watching.find(params[:watching_id])
    @children_watching.watching = @watching
    @child = Child.find(params[:children_watching][:child_id])
    @children_watching.child = @child
    if @children_watching.save
      redirect_to watching_children_watchings_path(@watching)
    end
  end

  def destroy
    @children_watching = ChildrenWatching.find(params[:id])
    @watching = @children_watching.watching
    @children_watching.destroy
    redirect_to watching_children_watchings_path(@watching)
  end
end

app/views/children_watchings/index.html.erb
<div class="btn">
  <i class="fas fa-chevron-left"></i>
  <%= link_to 'Retour', program_path(@watching.program) %>
</div>

<div class="bg-wrapper">
  <div class="wrapper">
    <div class="bg-grey my-5 p-5">
      <h4 class="text-center wrapper-title">Qui participe à la séance ?</h4>
      <div class="w-100 text-center">

        <div class="container-children-watching">
          <div class="card-child-avatar">
            <% current_user.children.each do |child| %>
              <% if child.watchings.where(id: params[:watching_id]).any?  %>
                <%= link_to children_watching_path(child.find_child_watchings(@watching)), method: :delete do %>
                  <div class="child-children_watching">
                    <% if child.photo.attached? %>
                      <%= cl_image_tag child.photo.key, class: "avatar-bordered" %>
                    <% end %>
                    <h3 class=""><%= child.name %></h3>
                  </div>
                <% end %>
                <%#= on affiche le avatar du sale gosse entouré de bleu %>
              <% else %>
                <%= simple_form_for([@watching, @children_watching]) do |f| %>
                  <%= f.hidden_field :child_id, value: child.id %>
                  <%= button_tag type: 'submit' do %>
                    <div class="child-children_watching-present">
                      <% if child.photo.attached? %>
                        <%= cl_image_tag child.photo.key, class: "avatar-large", alt: "avatar-large" %>
                      <% end %>
                      <h3 class="pt-3"><%= child.name %></h3>
                    </div>
                  <% end %>
                <% end %>
                <%#= on affiche le avatar sans cercle bleu %>
              <% end %>
            <% end %>
          </div>
          <%#= lien vers la vidéo sur la plateforme %>
          <% if @children_watchings.present? %>
            <div class="btn-orange">
              <%= link_to "Votre séance !", @watching.program.program_url, :target => "_blank" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>