config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :programs, only: [:index, :show] do
    resources :reviews, shallow: true
    resources :watchings, only: :create
    resources :favorites, only: [:create, :destroy]
  end

  get "/dashboard", to: "dashboards#show", as: :dashboard

  resources :children, only: [:create, :destroy]

  resources :watchings, except: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :children_watchings, only: [:index, :create]
  end
  resources :children_watchings, only: :destroy
  resources :accounts, only: [:new, :create, :destroy]
end

app/models/program.rb
class Program < ApplicationRecord
  CATEGORY = ["Documentaire", "Comédie", "Animation", "Educatif", "Aventure", "Fantastique", "Action"]
  LENGTH = ["0-25", "25-50", "50-100", "100-200"]

  belongs_to :platform
  has_many :watchings
  has_many :children_watchings, through: :watchings
  has_many :reviews
  has_many :favorites
  validates :title, presence: true, uniqueness: true
  validates :min_age, numericality: { greater_than_or_equal_to: 1 }
  validates :max_age, numericality: { only_integer: true }
  has_one_attached :photo

  def find_user_favorites(current_user)
    self.favorites.find_by(user: current_user)
  end

  def already_reviewed?(user)
    if reviews.present?
    reviews.select { |review| review.user == user }.any?
    end
  end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  def index
    @programs = Program.all
    return unless params[:request]

    if !(params[:request][:description].blank?)
      session[:search][:description] = params[:request][:description]
      sql_query = "programs.description @@ :description"
      description_programs = @programs.where(sql_query, description: "%#{params[:request][:description]}%")
      sql_query = "programs.title @@ :description"
      title_programs = @programs.where(sql_query, description: "%#{params[:request][:description]}%")
      @programs = description_programs + title_programs
    else
      session[:search][:description] = nil
    end
    if !(params[:request][:category].blank?)
      session[:search][:category] = params[:request][:category]
      sql_query = "programs.category @@ :category"
      @programs = @programs.where(sql_query, category: "#{params[:request][:category]}")
    else
      session[:search][:category] = nil
    end
    if !(params[:request][:max_age].blank?)
      max_age = params[:request][:max_age].to_i
      session[:search][:max_age] = max_age
      sql_query = "programs.max_age <= :max_age"
      @programs = @programs.where(sql_query, max_age: max_age)
    else
      session[:search][:max_age] = nil
    end
    if !(params[:request][:length].blank?)
      session[:search][:length] = params[:request][:length]
      min_length = params[:request][:length].split("-").first.to_i
      max_length = params[:request][:length].split("-").last.to_i
      sql_query = "programs.length >= :min_length AND programs.length < :max_length"
      @programs = @programs.where(sql_query, min_length: min_length, max_length: max_length)
      else
        session[:search][:length] = nil
    end
  end

  def show
    @program = Program.find(params[:id])
    @review = Review.new
    @watching = Watching.find_by_program_id(@program)
    @already_reviewed = @program.already_reviewed?(current_user)
  end
end

app/views/programs/_review.html.erb
<div class="review-container text-center">

  <% if @watching && !@already_reviewed %>
      <h4 class="text-center pb-5 wrapper-title">Laissez un commentaire :</h4>
      <div class="review">
        <%= simple_form_for [@program, @review] do |f| %>
          <%= f.input :content, label: false, input_html: { class: "border-blue"} %>
          <%= f.input :rating, as: :hidden  %>
          <div class="my-3">
            <% Review::AUTHORIZED_RATINGS.each do |index| %>
              <i id="<%= index %>" class="review-rating far fa-star"></i>
            <% end %>
          </div>
          <%= f.submit class: "btn-orange", value: "Valider" %>
        <% end %>
      </div>
    <% else %>
    <h4 class="text-center pb-5 wrapper-title">Commentaires :</h4>
  <% end %>



      <% if @program.present? %>
        <% @program.reviews.each do |review| %>
          <div class="reviews-card border-blue">
              <div class="user-review">
                  <h4><%= review.username %></h4>
                  <time datetime="#" class="card__date"><%= review.created_at.strftime("%d/%m/%y") %></time>
              </div>
              <div class="rating-review">
                    <% Review::AUTHORIZED_RATINGS.each do |number| %>
                      <i class="fa<%= (number > review.rating) ? 'r' : 's' %> fa-star"></i>
                    <% end %>
                    <h3><%= review.content %></h3>
              </div>
          </div>
        <% end %>
      <% end %>
</div>

app/views/programs/index.html.erb
<div class="bg-wrapper">
  <div class="wrapper">
    <%# search-bar %>
    <%= render 'shared/searchbar' %>
    <%# liste de tous les programmes %>
    <% @programs.each do |program| %>
      <div class="program_card" id="program">
        <div class="info_section">
          <div class="program_header">
            <% if program.photo.attached? %>
              <%= cl_image_tag program.photo.key,class:"locandina", crop: :fill %>
            <% else %>
              <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" class="card__image" alt="" />
            <% end %>
            <h2><%= program.title %></h2>
            <h4><%= program.category %></h4>
            <span class="minutes"><%= program.length %> min</span>
            <p class="age">A partir de <%= program.min_age %> ans</p>
          </div>
          <div class="program_desc">
            <p class="text">
              <%= program.description.first(180) %>
            </p>
          </div>
          <div class="program_social">
            <ul>
              <li>
                <% if program.find_user_favorites(current_user)%>
                  <%= link_to  program_favorite_path(program, program.find_user_favorites(current_user)), method: :delete do%>
                    <i class="fas fa-heart"></i>
                  <% end %>
                <% else %>
                  <%= link_to program_favorites_path(program), method: :post do%>
                    <i class="far fa-heart"></i>
                  <% end %>
                <% end %>
              </li>
              <li><%= link_to "Voir plus...", program_path(program), id:"link-show" %></li>
            </ul>
          </div>
        </div>
        <div class="blur_back program_back">
          <%= cl_image_tag program.photo.key, crop: :fill %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/programs/show.html.erb
<div class="btn">
  <i class="fas fa-chevron-left"></i>
  <%= link_to 'Retour à la liste des programmes', programs_path %>
</div>
<%# div qui englobe la page show : %>
<div class="program-container">
    <%# div qui engloge la banner donc l'image majoritairement %>
    <div class="program-banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @program.photo.key, crop: :fill %>')">
      <%# englobe le titre et les boutons sur l'image de la banner %>
      <div class="program-banner-text">
        <h1><strong><%= @program.title %></strong></h1>
        <div class="program-banner-btn">
          <%= link_to "Regarder sur #{@program.platform.name}", program_watchings_path(@program), method: :post, class: "btn-orange" %>
          <button class="btn-orange"><span>Voir la bande-annonce</span></button>
        </div>
      </div>
    </div>
    <div class="bg-wrapper">
      <div class="wrapper">
        <div class="program-item bg-grey">
            <h4 class="text-center pb-5 wrapper-title"><%= @program.title %></h4>
            <div class="program-categ-and-age">
              <%# <h1><strong><@program.title></strong></h1> %>
              <div class="show-categ"><h2><%= @program.category %></h2></div>
              <div class="show-age-range"><h3>De <%= @program.min_age %> à <%= @program.max_age %> ans</h3></div>
            </div>
            <p><%= @program.description %></p>
        </div>

        <%# à partir de cet endroit, avis laissés sur le programme en question. boucle for each à rajouter %>

        <div class="program-item bg-grey">
          <%= render 'programs/review' %>
        </div>
      </div>
    </div>
</div>