config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :programs, only: [:index, :show] do
    resources :reviews, shallow: true
    resources :watchings, only: :create
    resources :favorites, only: [:create, :destroy]
  end

  get "/dashboard", to: "dashboards#show", as: :dashboard

  resources :children, only: [:create, :destroy]

  resources :watchings, except: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :children_watchings, only: [:index, :create]
  end
  resources :children_watchings, only: :destroy
  resources :accounts, only: [:new, :create, :destroy]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<%# footer ci-dessous : %>

<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    @2021 - Copyright - Tous droits réservés <br> Créé par PliSiTol avec <i class="fas fa-heart"></i>
  </div>
</div>

<%# fin du footer %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="navbar-brand-logo-name">
    <%= link_to root_path, class: 'navbar-brand' do %>
      <%= image_tag "PliSiTol.png", alt: "Logo PliSiTol" %>
    <% end %>
      <div class="navbar-brand-name">PliSiTol</div>
  </div>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <%# <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
          <%= link_to "déconnecter", "#", class: "dropdown-item" %>
        </div>
      <li class="nav-item active">
        <% if !current_user %>
          <%= link_to 'Se connecter', new_user_session_path, class: "nav-link" %>
        <% end %>
      </li>
      <li class="nav-item dropdown">
        <%# <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% if user_signed_in? %>
          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "https://thispersondoesnotexist.com/image", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
            <%= link_to "déconnecter", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        <% else %>
        <% end %>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_searchbar.html.erb
  <div class="container-home-form">
    <div class="home-form">
      <%= simple_form_for :request, url: programs_path, method: :get do |f| %>
        <div class="home-form-text-field">
        <%= f.input :description, placeholder: "Titre, description...", label: false, required: false, input_html: { value: session[:search][:description] } %>
        </div>
        <div class="home-form-categ-field">
        <%= f.input :category, collection: [""] + Program::CATEGORY, prompt: "Catégorie", label: false, required: false, selected: session[:search][:category] %>
        </div>
        <div class="home-form-age-field col-3">
        <%= f.input :max_age, label: false, placeholder: "Jusqu'à... ans", as: :numeric, input_html: { min: 0, value: session[:search][:max_age] }, required: false %>
        </div>
        <div class="home-form-length-field">
        <%= f.input :length, collection: [["all", ""]] + Program::LENGTH.map { |l| [l, l]}, prompt: "Durée", label: false, required: false, selected: session[:search][:length] %>
        </div>
        <div class="home-form-submit-btn">
          <%= button_tag type: 'submit' do %>
            <i class="fas fa-search"></i>
          <% end %>
        </div>
     <% end %>
    </div>
  </div>