config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :programs, only: [:index, :show] do
    resources :reviews, shallow: true
    resources :watchings, only: :create
    resources :favorites, only: [:create, :destroy]
  end

  get "/dashboard", to: "dashboards#show", as: :dashboard

  resources :children, only: [:create, :destroy]

  resources :watchings, except: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :children_watchings, only: [:index, :create]
  end
  resources :children_watchings, only: :destroy
  resources :accounts, only: [:new, :create, :destroy]
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @accounts = current_user.accounts
    @platforms = current_user.platforms
    @watchings = current_user.watchings
    @favorites = current_user.favorites
    @children = current_user.children
    @child = Child.new
    @account = Account.new
    # @data_child = @children.first.calculate_cw_all_categories
    # @line_data_child = @children.calculate_cw_all_dates
  end
end

app/views/dashboards/_activities.html.erb
<div class="container-activities my-5 pb-5 bg-grey">
  <h4 class="text-center py-5 wrapper-title">Mon historique :</h4>
    <div class="wrapper-activities">
      <div class="grid-program-activities">
        <% current_user.watchings&.group_by{ |w| w.program_id}&.values&.each do |watchings| %>
          <div class="card-program-activities" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path watchings.last.program.photo.key, crop: :fill %>')" >
              <h4>
                <%= watchings.last.program.title %>
              </h4>
              <p><%= watchings.count %> vues </p>
            <div class="watch-date"><%= watchings.last.created_at.strftime("%d/%m/%y") %></div>
          </div>
        <% end %>
      </div>
  </div>
</div>

  <div class="wrapper-activities bg-grey pb-5">
    <h4 class="text-center py-5 wrapper-title">Mes favoris :</h4>
      <div class="grid-program-activities">
        <% current_user.favorites.each do |favorite| %>
          <div class="card-program-activities" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path favorite.program.photo.key, crop: :fill %>')" >
            <h4>
              <%= favorite.program.title %>
            </h4>
          </div>
        <% end %>
      </div>
    </div>

  <div class="activities-reviews-list pb-5 bg-grey">
    <h4 class="text-center py-5 mt-5 wrapper-title">Mes avis :</h4>
      <% if current_user.reviews.present? %>
        <div class="wrapper-activities">
          <div class="grid-reviews-activities">
            <% current_user.reviews.each do |review| %>

            <div class="card text-center review-card" style="width: 18rem;">
              <%= cl_image_tag review.program.photo.key, class: "card-img-top" %>
              <div class="card-body">
                <h5 class="card-title"><%= review.program.title %></h5>
                <time datetime="#" class="card__date"><%= review.created_at.strftime("%d/%m/%y") %></time>
                <div class="rating-review">
                    <p class="card-text"><%= review.content %></p>

                    <% Review::AUTHORIZED_RATINGS.each do |number| %>
                      <i class="fa<%= (number > review.rating) ? 'r' : 's' %> fa-star"></i>
                    <% end %>
                </div>
              </div>
            </div>
      <% end %>
          </div>
        </div>
      <% end %>
  </div>

app/views/dashboards/_general.html.erb
<div class="general-wrap">

<div class="bg-grey my-5">
<h4 class="text-center py-5 wrapper-title">Enfants hébergés sur mon compte :</h4>
  <div class="general-kids-list align-items-start">
    <% current_user.children.each do |child| %>
      <div class="general-kids-item text-center">
        <%# if Rails.application.assets.present? %>
          <%# if Rails.application.assets.resolve("avatars/#{c.image_url}.png").first %>
            <%#= image_tag "avatars/#{c.image_url}", class: "avatar-large", alt: "avatar-large"%>
            <%= cl_image_tag child.photo.key, class: "avatar-large", alt: "avatar-large"%>
            <h3><%= child.name %></h3>
          <%# end %>
        <%# end %>
        <%= link_to child_path(child),
          method: :delete,
          data: { confirm: "êtes vous sûr(e) de vouloir supprimer cet enfant?" } do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
      </div>
    <% end %>
  <button id="create-child"><i class="fas fa-plus-circle cross"></i></button>

  <div class="child-add-form disable">
    <%= simple_form_for child do |f| %>
      <%= f.input :name, label: "Prénom"%>
      <%= f.input :age %>
      <div class="avatar-form">
        <%= f.input :image_url,
                    as: :radio_buttons,
                    collection:
                      [
                        [(cl_image_tag 'avatar1_bhgzro')],
                        [(cl_image_tag 'avatar2_k6kdsu')],
                        [(cl_image_tag 'avatar3_hzyhpj')],
                        [(cl_image_tag 'avatar4_vuugti')],
                        [(cl_image_tag 'avatar5_omemxm')],
                        [(cl_image_tag 'avatar6_lwmilx')],
                        [(cl_image_tag 'avatar7_bfovko')],
                        [(cl_image_tag 'avatar8_mmmtof')]
                      ],
                    label_method: :first,
                    value_method: :last,
                    input_html: {data: {form_target: 'input'}, class: "avatar-large avatar-field"}
        %>
      </div>
      <%= f.button :submit%>
    <% end %>
  </div>
  </div>
</div>
<div class="bg-grey my-5 pb-5">
<h4 class="text-center py-5 wrapper-title">Mes comptes :</h4>
  <div class="general-accounts-list flex-wrap">
  <% current_user.platforms.each do |p| %>
    <div class="general-accounts-item">
      <%= link_to account_path(current_user.accounts.find_by(platform: p)),
          method: :delete,
          data: { confirm: "êtes vous sûr(e) de vouloir supprimer ce compte?" } do %>
          <%= cl_image_tag(p.photo.key, class: "platform-avatar") %>
      <% end %>
    </div>
  <% end %>
<button id="add-account"><i class="fas fa-plus-circle cross"></i></button>

  <div class="account-add-form border-blue p-3 disable">
    <%= simple_form_for @account do |f| %>
      <%= f.association :platform, label: false, prompt: "Compte" %>
      <%= f.button :submit, "Ajouter un compte", class: "btn btn-orange" %>
    <% end %>
  </div>
  </div>
</div>
</div>

app/views/dashboards/show.html.erb
  <div class="bg-wrapper py-5">
    <div class="wrapper">

        <nav>
          <div class="nav nav-tabs" id="nav-tab" role="tablist">
            <a class="nav-link tier-nav active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">Général</a>
            <a class="nav-link tier-nav-plus-one" id="nav-activities-tab" data-toggle="tab" href="#nav-activities" role="tab" aria-controls="nav-activities" aria-selected="false">Activités</a>
            <a class="nav-link tier-nav" id="nav-stats-tab" data-toggle="tab" href="#nav-stats" role="tab" aria-controls="nav-stats" aria-selected="false">Statistiques</a>
          </div>
        </nav>

        <div class="tab-content" id="nav-tabContent">
          <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
            <%= render 'general', child: @child %>
          </div>
          <div class="tab-pane fade" id="nav-activities" role="tabpanel" aria-labelledby="nav-activities-tab">
            <%= render 'activities', account: @account %>
          </div>
          <div class="tab-pane fade" id="nav-stats" role="tabpanel" aria-labelledby="nav-stats-tab">
            <script src="https://code.highcharts.com/modules/series-label.js"></script>
            <script src="https://code.highcharts.com/highcharts.js"></script>
            <script src="https://code.highcharts.com/modules/export-data.js"></script>
            <script src="https://code.highcharts.com/modules/accessibility.js"></script>

      <div class="bg-white mt-5">
        <h4 class="text-center py-5 wrapper-title">Statistiques :</h4>
        <div class="d-flex justify-content-around">
          <% @children.each do |child| %>
          <div class="text-center">
            <%= cl_image_tag child.photo.key, class: "avatar-large", alt: "avatar-large"%>
            <h3><%= child.name %></h3>
            <figure class="highcharts-figure">
                <div id="pie-chart-container-<%= child.id %>" class="pie-chart" data-categories="<%= child.calculate_cw_all_categories %>"></div>
            </figure>
          </div>
          <% end %>
        </div>
      </div>
      <div class="bg-white my-5">
        <h4 class="text-center py-5 wrapper-title">Global :</h4>
        <figure class="highcharts-line-chart">
            <div id="line-chart-container" data-set="<%= @children.calculate_cw_all_dates %>"></div>
        </figure>
      </div>
      </div>
    </div>
  </div>
</div>